---
linters:
  enable:
    - misspell
    - revive

linters-settings:
  errcheck:
    exclude-functions:
      # Used in HTTP handlers, any error is handled by the server itself.
      - (net/http.ResponseWriter).Write
      # Never check for logger errors.
      - (github.com/go-kit/log.Logger).Log
  revive:
    rules:
      - name: unused-parameter
        disabled: true
